# Generated by Django 2.2.12 on 2023-10-02 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mebels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bed',
            old_name='lenght',
            new_name='length',
        ),
    ]
