# Generated by Django 4.2.5 on 2023-10-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebels', '0002_auto_20231002_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='base_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='base_he',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='color_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='color_he',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
