# Generated by Django 5.1.2 on 2024-10-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebels', '0003_bed_base_en_bed_base_he_bed_color_en_bed_color_he'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
